FROM node:20-alpine

RUN npm install -g serve

WORKDIR /app

COPY . .

RUN npm install --include=dev

RUN npx turbo run build --filter=tma-landing

EXPOSE 53004

CMD ["serve", "-s", "apps/tma-landing/dist", "-p", "53004"]
