version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: grupiah_postgres
    environment:
      POSTGRES_USER: grupiah_admin
      POSTGRES_PASSWORD: grupiah_password
      POSTGRES_DB: grupiah_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grupiah_net

  redis:
    image: redis:7-alpine
    container_name: grupiah_redis
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    networks:
      - grupiah_net

volumes:
  postgres_data:
  redis_data:


networks:
  grupiah_net:
    driver: bridge
