[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate --schema=./packages/database/prisma/schema.prisma",
  "npx turbo run build --filter=api",
  "npm prune --production"
]

[start]
cmd = "npx prisma db push --accept-data-loss --schema=./packages/database/prisma/schema.prisma && node apps/api/dist/main.js"
