[phases.install]
cmds = ["npm install", "npm install -g prisma turbo"]

[phases.build]
cmds = [
  "turbo run build --filter=grupiah-api",
  "npm prune --production"
]

[start]
cmd = "npx prisma generate --schema=./packages/database/prisma/schema.prisma && npx prisma db push --accept-data-loss --schema=./packages/database/prisma/schema.prisma && node apps/api/dist/main.js"
